# Generated by Django 5.1.4 on 2025-01-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bissextile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_utilise', models.CharField(max_length=100)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('annee_debut', models.IntegerField(blank=True, null=True)),
                ('annee_fin', models.IntegerField(blank=True, null=True)),
                ('is_bissextile', models.BooleanField(blank=True, null=True)),
                ('annees_bissextiles', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
